version: '3.2'

services:
    my_django:
      build: .
      stdin_open: true
      tty: true
      ports:
        - "8000:8000"
      working_dir: /app
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - ../sample:/app
      environment:
        - "PYTHONUNBUFFERED=1"
      expose:
        - "8000"
      depends_on:
        - mariadb
      

    mariadb:
      image: mariadb:10.2
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mydb
        MYSQL_USER: myusername
        MYSQL_HOST: localhost
        MYSQL_PASSWORD: mypassword
      volumes:
       - ../data/mariadb:/var/lib/mysql

    